compiler: ghc-9.4.8
resolver: lts-21.14

packages:
- .

extra-deps:
- git: https://github.com/manifoldvalley/alga
  commit: '01a42337b7f5845ce0c4df7d49cfd6949a78d8a7'
- data-partition-0.3.0.0

ghc-options:
  "$locals": -fwrite-ide-info



